### ISSUE TITLE
如何兼容minSdkVersion 17

### ISSUE THREAD

**Issue by match567** [GitHubZJY/XTableView#3]
我的项目最低版本要求是17，但是引用该插件需要最低21的版本。整合上去一堆错误

**Comment by GitHubZJY** [comment]
因为目前组件是基于androidx开发的

**Comment by match567** [comment]
> 因为目前的组件是基于androidx开发的

谢谢。我做了升级调整后能正常运行了，不过最后还是取消使用了，不太适合我们业务场景。
